### ISSUE TITLE
Mudar api_root_url para incluir sandbox-app

### ISSUE THREAD

**Issue by muriloazevedo** [allisson/python-vindi#1]
Estou fazendo a integração, porém senti falta de uma opção para modificar a api_root_url porque é necessário fazer testes em sandbox. Não existe essa opção ainda, correto?

**Comment by allisson** [comment]
É verdade, vou lançar a versão 0.2.0 com essa opção.

**Comment by allisson** [comment]
Versão 0.2.0 no ar :)
